spring:
  datasource:
    # >=6.x com.mysql.cj.jdbc.Driver
    # <=5.x com.mysql.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/content_center?characterEncoding=utf8&useSSL=false
    hikari:
      username: root
      password: 123456
  cloud:
    nacos:
      discovery:
        # 指定nacos server 地址  注意：地址前面不要加协议，直接指定IP/域名就可以了
        server-addr: 117.50.105.135:15098
        # 集群名称
        cluster-name: BJ
        metadata:
          # 自己这个实例的版本
          version: v1
          # 允许调用的提供者版本
          target-version: v1
    sentinel:
      filter:
        # 打开/关闭对Spring MVC 端点的保护
        enabled: true
      transport:
        # 指定sentinel控制台的地址
        dashboard: localhost:8080
#      datasource:
#        # 名称随意
#        flow:
#          nacos:
#            server-addr: 117.50.105.135:15098
#            dataId: ${spring.application.name}-flow-rules
#            groupId: SENTINEL_GROUP
#            # 规则类型，取值见：
#            # org.springframework.cloud.alibaba.sentinel.datasource.RuleType
#            rule-type: flow
#        degrade:
#          nacos:
#            server-addr: 117.50.105.135:15098
#            dataId: ${spring.application.name}-degrade-rules
#            groupId: SENTINEL_GROUP
#            rule-type: degrade
#        system:
#          nacos:
#            server-addr: 117.50.105.135:15098
#            dataId: ${spring.application.name}-system-rules
#            groupId: SENTINEL_GROUP
#            rule-type: system
#        authority:
#          nacos:
#            server-addr: 117.50.105.135:15098
#            dataId: ${spring.application.name}-authority-rules
#            groupId: SENTINEL_GROUP
#            rule-type: authority
#        param-flow:
#          nacos:
#            server-addr: 117.50.105.135:15098
#            dataId: ${spring.application.name}-param-flow-rules
#            groupId: SENTINEL_GROUP
#            rule-type: param-flow
  application:
    # 服务名称尽量用中划线“-” ，不要使用下划线“_”，更不要用特殊字符
    name: content-center
  main:
    # 允许同名（feign client 中name同名）
    allow-bean-definition-overriding: true
server:
  port: 8010

# 实现通过ribbon在调用 user-center 时使用com.netflix.loadbalancer.RandomRule 规则
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
# 开启饥饿加载
ribbon:
  eager-load:
    enabled: true  # 开启饥饿加载
    clients: user-center  # 为哪些微服务开启饥饿加载（细粒度配置）
logging:
  level:
    cn.zbq.springcloud.contentcenter.feignclient.UserCenterFeignClient: debug
    cn.zbq.springcloud.contentcenter.feignclient.TestBaiduFeignClient: debug
feign:
  sentinel:
    # 为feign 整合sentinel
    enabled: true
  client:
    config:
      # 全局日志级别配置
      default:
        loggerLevel: full
  httpclient:
    # 让feign使用apache httpclient做请求，而不是默认的url connection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50
management:
  endpoints:
    web:
      exposure:
        include: '*'
resttemplate:
  sentinel:
    # 关闭@SentinelRestTemplate注解
    enabled: true
rocketmq:
  name-server: 117.50.105.135:9876
  producer:
    # 必须指定group
    group: test-group