spring:
  datasource:
    # >=6.x com.mysql.cj.jdbc.Driver
    # <=5.x com.mysql.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/content_center?characterEncoding=utf8&useSSL=false
    hikari:
      username: root
      password: 123456
  cloud:
    nacos:
      discovery:
        # 指定nacos server 地址  注意：地址前面不要加协议，直接指定IP/域名就可以了
        server-addr: 117.50.105.135:15098
        # 集群名称
        cluster-name: BJ
        metadata:
          # 自己这个实例的版本
          version: v1
          # 允许调用的提供者版本
          target-version: v1
  application:
    # 服务名称尽量用中划线“-” ，不要使用下划线“_”，更不要用特殊字符
    name: content-center

server:
  port: 8010

# 实现通过ribbon在调用 user-center 时使用com.netflix.loadbalancer.RandomRule 规则
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
# 开启饥饿加载
ribbon:
  eager-load:
    enabled: true  # 开启饥饿加载
    clients: user-center  # 为哪些微服务开启饥饿加载（细粒度配置）